- when: (_wg_cfg_hook.src is not none) and (_wg_cfg_hook.dest is not none)
  vars:
    is_template: "{{ _wg_cfg_hook.src.endswith('.j2') }}"
    name: "{{ _wg_cfg_hook.name }}"
    src: "{{ _wg_cfg_hook.src }}"
    dest: "{{ _wg_cfg_hook.dest }}"
  block:
    - when: is_template | bool
      name: >-
        Template {{ name }} script {{ src | f }} → {{ dest | f }}
      template:
        src: "{{ src }}"
        dest: "{{ dest }}"
        mode: '0700'
    
    - when: not (is_template | bool)
      name: >-
        Copy {{ name }} script
        {{ src | nrser.nansi.rel }} → {{ dest | nrser.nansi.rel }}
      copy:
        src: "{{ src }}"
        dest: "{{ dest }}"
        mode: '0700'