- delegate_to: "{{ wg_cfg_client_config_delegate_to }}"
  vars:
    ansible_user: "{{ wg_cfg_client_config_delegate_to_user }}"
  become: false
  block:
    - name: >-
        Create directory to save generated client configs at
        {{ wg_cfg_client_config_dir | f }}
      file:
        path: "{{ wg_cfg_client_config_dir }}"
        state: directory
        mode: '0700'

    - when: wg_cfg_client_config_rm_old
      name: >-
        Remove existing files in client config dest
        {{ (wg_cfg_client_config_dir, '*.conf') | join | f }}
      with_fileglob:
        - "{{ wg_cfg_client_config_dir }}/*.conf }}"
      file:
        path: "{{ wg_cfg_client_config_dir }}/{{ item }}"
      
    - name: >-
        Save generated client configs to {{ wg_cfg_client_config_dir | f }}
      with_dict: "{{ wg_cfg_update_rsp.client_configs }}"
      copy:
        content: "{{ item.value }}"
        dest: "{{ wg_cfg_client_config_dir }}/{{ item.key }}.conf"
        mode: '0600'
      no_log: "{{ wg_cfg_no_log }}"
