# https://www.postgresql.org/download/linux/debian/
# 
# (same as https://www.postgresql.org/download/linux/ubuntu/)
# 

- set_fact:
    pg_deb_pkgs: >-
      {{
        ( pg_version, pg_client, pg_contrib, pg_frontend_dev, pg_backend_dev )
        | pg_deb_pkg_list
      }}

- name: Install the gpg key for www.postgresql.org
  apt_key:
    id: 790BC7277767219C42C86F933B4FE6ACC0B21F32
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
    
- name: Add apt.postgresql.org repo
  apt_repository:
    repo: >-
      deb http://apt.postgresql.org/pub/repos/apt
      {{ ansible_facts.distribution_release }}-pgdg main
    state: present
    update_cache: yes

- name: >-
    Manage packages {{ pg_deb_pkgs | join(', ') }}
  apt:
    pkg: "{{ pg_deb_pkgs }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: >-
    Manage {{ pg_service_name }} service
  service:
    name: "{{ pg_service_name }}"
    enabled: "{{ pg_service_enabled }}"
    state: "{{ pg_service_state }}"
