---
# https://docs.ansible.com/ansible/latest/modules/user_module.html
# https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html
# 

- name: >-
    Create admin group {{ humans_admin_group | f }}
  group:
    name: "{{ humans_admin_group }}"
    state: present

- name: >-
    Create humans group {{ humans_group | f }}
  group:
    name: "{{ humans_group }}"
    state: present

- name: >-
    Allow {{ humans_admin_group | f }} group to have password-less sudo
  lineinfile:
    dest: "{{ humans_sudoers_path }}"
    state: present
    regexp: '^%{{ humans_admin_group }}'
    line: '%{{ humans_admin_group }} ALL=(ALL) NOPASSWD: ALL'
  
- with_items: "{{ humans }}"
  name: Create human users
  user:
    name: "{{ item.name }}"
    state: present
    create_home: true
    shell: /bin/bash

- with_items: "{{ humans }}"
  name: >-
    Add all human users to {{ humans_group | f }} group
  user:
    name: "{{ item.name }}"
    groups: "{{ humans_group }}"
    append: true

- with_items: "{{ humans }}"
  when: item.admin | default( false )
  name: >-
    Add admin users to {{ humans_admin_group | f }} group
  user:
    name: "{{ item.name }}"
    groups: "{{ humans_admin_group }}"
    append: true
  # command: "usermod -aG admin {{ item.name }}"
  
- with_items: "{{ humans }}"
  name: Set the user ssh keys from their ones on GitHub
  authorized_key:
    user: "{{ item.name }}"
    key: "https://github.com/{{ item.github }}.keys"
    exclusive: "{{ humans_authorized_key_exclusive }}"

- when: humans_auth_admins_as_users
  loop: "{{ humans_admins }}"
  loop_control:
    loop_var: _admin
  include_tasks: "{{ role_path }}/tasks/_auth_admin_as_users.yaml"

# it's much more secure to use ssh keys
- name: Disallow SSH password authentication
  lineinfile:
    dest: "{{ humans_sshd_config_path }}"
    regexp: "^\\#?PasswordAuthentication"
    line: PasswordAuthentication no
    state: present
  notify: ssh_restart

# turning off root ssh access is a security best practice
- name: Disallow root SSH access
  lineinfile:
    dest: "{{ humans_sshd_config_path }}"
    regexp: "^PermitRootLogin"
    line: PermitRootLogin no
    state: present
  notify: ssh_restart

- name: >-
    **ONLY** allow SSH login for humans group {{ humans_group | f }}
  lineinfile:
    dest: "{{ humans_sshd_config_path }}"
    regexp: "^\\#?AllowGroups"
    line: "AllowGroups {{ humans_group }}"
    state: present
  notify: ssh_restart

- with_items: "{{ humans }}"
  loop_control:
    loop_var: user
  when: "humans_git and 'git' in user"
  include_tasks: "{{ role_path }}/tasks/_git_config.yaml"
